### ISSUE TITLE
Load Process Program Cepat

### ISSUE THREAD

**Issue by bimbi19** [alfrcr/ilearn#1]
Saya mau tanya gimana cara config supaya project laravel bisa cepat seperti web ilearn ini, sekian dan trima kasih

**Comment by alfrcr** [comment]
kalau yg saya terapkan sih ini:
1. Jalankan `php artisan route:cache`, `php artisan config:cache` dan `php artisan optimize` (untuk production). Dan kalau target user indonesia, lebih baik beli server yg di indonesia.
2. Pakai eager-loading
3. File css + js saya jadikan satu bundle dan di-minimize lainnya pakai cdn.
