### ISSUE TITLE
Failed Upload Gambar Profile Picture

### ISSUE THREAD

**Issue by ignzdave** [alfrcr/ilearn#2]
Errornya kenapa ya? pas mw ganti pp user dan upload gambar langsung seperti dibawah ini..

![failed upload picture](https://cloud.githubusercontent.com/assets/6700124/16918198/2efd31e0-4d37-11e6-8627-35004c831813.png)

**Comment by alfrcr** [comment]
itu ganti foto profil yg dihalaman mana ya? @ignzdave

**Comment by ignzdave** [comment]
Kalo saya sih td pas login jd guru. Trus coba ganti pp di halaman profile.. Saya masi blm terlalu pajam laravel jd td cuma liat2 coding nya aja hahaha.. Krn baru belajar juga.. Terima kasih udah di kasi jawabannya bsk baru bisa coba hehehe

**Comment by alfrcr** [comment]
oh iya maaf mas @ignzdave, ternyata bukan itu masalahnya.
Masalahnya uuid.v1 yg saya pakai kalau di sistem 32-bit membutuhkan package [moontoast/math](https://github.com/moontoast/math). Jadi utk fix error ini silakan install package _moontoast/math_ dulu. Bisa dilihat di [sini](https://github.com/moontoast/math#installation)

**Comment by ignzdave** [comment]
Udah Fix ya.. Btw kok gak di tambahin di composer.json dari file project? malah d tambah di readme hahaha

**Comment by alfrcr** [comment]
udah jarang pc 32-bit skrg mas hehehe, itu pertimbangan saya

**Comment by ignzdave** [comment]
@alfrcr : PC saya 64-bit loh.. tp kok masih perlu sprt itu ya? hehehe .. Apa OS Win 7 64-bit saya KW1 kali ya hahahaha

**Comment by alfrcr** [comment]
hmm, kurang tau jg mas. Tp yang jelas di dokumentasi Ramsey UUID error itu muncul kalau os yg terinstall 32-bit
